### ISSUE TITLE
Blue colour banding

### ISSUE THREAD

**Issue by Maxoos** [mattdesl/glsl-lut#1]
Thanks for this lovely thing! However, there seem to be a banding issue on the blue colour. Have a look at this sample:

![blue_issue](https://cloud.githubusercontent.com/assets/1913291/9685488/07492af2-5362-11e5-9ed9-a7158973c15f.jpg)

This is the LUT image being used:
![full_negative_hue](https://cloud.githubusercontent.com/assets/1913291/9685512/28dccc00-5362-11e5-857a-25b752d1e913.jpg)

Would love to find a fix for this...
Thanks!

**Comment by mattdesl** [comment]
Are you using `gl.LINEAR` for both directions? Does the banding appear with the default LUT provided in the repo?

It might be a limitation of the algorithm; since we are not using a true 3D LUT but a pseudo-LUT in 2 directions.

Could also try changing some things to `highp` (instead of `lowp`) in the shader.

**Comment by mattdesl** [comment]
Ok, I just tested and your lookup table is causing the banding. It's probably because you saved with JPG which is a lossy format.

Try taking the [original PNG](https://github.com/mattdesl/glsl-lut/blob/master/image/lookup.png) and then apply your adjustments and save as PNG-24 (lossless).

**Comment by Maxoos** [comment]
Thank you for looking into this.

I tried again with the original LUT, imported into Adobe Lightroom, moved all HUE in HSL to -80 and exported as TIF. Converted to uncompress PNG using Photoshop. It did not make a difference so I think there is a different issue.

Please see this TIFF file out of lightroom.
https://drive.google.com/file/d/0B9XeYSGwr2ZSRTFrMXkwdWViOUk/view?usp=sharing

**Comment by Maxoos** [comment]
Ok so i've accidentally left the color nice reduction on, and so it created some artefacts. Thanks for your time :)

**Comment by mattdesl** [comment]
Cool! :smile:
