### ISSUE TITLE
Use an alternative to the Lenna image

### ISSUE THREAD

**Issue by juliendargelos** [mattdesl/glsl-lut#5]
Hi,

The Lenna image used in the demo, which originates from Playboy magazine, is very often criticized:

> The use of the image has produced controversy because Playboy is "seen (by some) as being degrading to women".[[21]](https://en.wikipedia.org/wiki/Lenna#cite_note-Munson-21) In a 1999 essay on reasons for the male predominance in computer science, applied mathematician [Dianne P. O'Leary](https://en.wikipedia.org/wiki/Dianne_P._O%27Leary) wrote:
> > Suggestive pictures used in lectures on image processing ... convey the message that the lecturer caters to the males only. For example, it is amazing that the "Lena" pin-up image is still used as an example in courses and published as a test image in journals today.[[4]](https://en.wikipedia.org/wiki/Lenna#cite_note-oleary-4)

[Wikipedia](https://en.wikipedia.org/wiki/Lenna#Criticism)

Would you consider using an alternative image ?

[USC-SIPI Image Database from University of Southern California](https://sipi.usc.edu/database/database.php?volume=misc)

**Comment by mattdesl** [comment]
Yes! It should be easy to swap the ‘lena’ dependency for ‘baboon-image’:

https://www.npmjs.com/package/baboon-image

PR welcome!
